<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1671024570297' stop='1671024571412'>
    <name>Local Storage</name>
    <title>Local Storage</title>
    <test-cases>
        <test-case start='1671024570297' status='broken' stop='1671024571356'>
            <name>cy.clearLocalStorage() - clear all data in local storage</name>
            <title>cy.clearLocalStorage() - clear all data in local storage</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>`cy.visit()` failed trying to load:
                
                https://example.cypress.io/commands/local-storage
                
                The response we received from your web server was:
                
                  > 404: Not Found
                
                This was considered a failure because the status code was not `2xx`.
                
                If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`
                
                Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Local Storage`</message>
                <stack-trace>CypressError: `cy.visit()` failed trying to load:
                
                https://example.cypress.io/commands/local-storage
                
                The response we received from your web server was:
                
                  > 404: Not Found
                
                This was considered a failure because the status code was not `2xx`.
                
                If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`
                
                Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Local Storage`
                    at http://localhost:63175/__cypress/runner/cypress_runner.js:140455:25
                    at visitFailedByErr (http://localhost:63175/__cypress/runner/cypress_runner.js:139830:12)
                    at http://localhost:63175/__cypress/runner/cypress_runner.js:140435:13
                    at tryCatcher (http://localhost:63175/__cypress/runner/cypress_runner.js:10798:23)
                    at Promise._settlePromiseFromHandler (http://localhost:63175/__cypress/runner/cypress_runner.js:8733:31)
                    at Promise._settlePromise (http://localhost:63175/__cypress/runner/cypress_runner.js:8790:18)
                    at Promise._settlePromise0 (http://localhost:63175/__cypress/runner/cypress_runner.js:8835:10)
                    at Promise._settlePromises (http://localhost:63175/__cypress/runner/cypress_runner.js:8911:18)
                    at _drainQueueStep (http://localhost:63175/__cypress/runner/cypress_runner.js:5505:12)
                    at _drainQueue (http://localhost:63175/__cypress/runner/cypress_runner.js:5498:9)
                    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:63175/__cypress/runner/cypress_runner.js:5514:5)
                    at Async.drainQueues (http://localhost:63175/__cypress/runner/cypress_runner.js:5384:14)
                From Your Spec Code:
                    at Context.eval (http://localhost:63175/__cypress/tests?p=cypress\integration\2-advanced-examples\local_storage.spec.js:102:8)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>